// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.7
// source: proto/client/client.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Client_Create_FullMethodName = "/Client/Create"
)

// ClientClient is the client API for Client service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (Client_CreateClient, error)
}

type clientClient struct {
	cc grpc.ClientConnInterface
}

func NewClientClient(cc grpc.ClientConnInterface) ClientClient {
	return &clientClient{cc}
}

func (c *clientClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (Client_CreateClient, error) {
	stream, err := c.cc.NewStream(ctx, &Client_ServiceDesc.Streams[0], Client_Create_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &clientCreateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Client_CreateClient interface {
	Recv() (*CreateRes, error)
	grpc.ClientStream
}

type clientCreateClient struct {
	grpc.ClientStream
}

func (x *clientCreateClient) Recv() (*CreateRes, error) {
	m := new(CreateRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClientServer is the server API for Client service.
// All implementations must embed UnimplementedClientServer
// for forward compatibility
type ClientServer interface {
	Create(*CreateReq, Client_CreateServer) error
	mustEmbedUnimplementedClientServer()
}

// UnimplementedClientServer must be embedded to have forward compatible implementations.
type UnimplementedClientServer struct {
}

func (UnimplementedClientServer) Create(*CreateReq, Client_CreateServer) error {
	return status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedClientServer) mustEmbedUnimplementedClientServer() {}

// UnsafeClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServer will
// result in compilation errors.
type UnsafeClientServer interface {
	mustEmbedUnimplementedClientServer()
}

func RegisterClientServer(s grpc.ServiceRegistrar, srv ClientServer) {
	s.RegisterService(&Client_ServiceDesc, srv)
}

func _Client_Create_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientServer).Create(m, &clientCreateServer{stream})
}

type Client_CreateServer interface {
	Send(*CreateRes) error
	grpc.ServerStream
}

type clientCreateServer struct {
	grpc.ServerStream
}

func (x *clientCreateServer) Send(m *CreateRes) error {
	return x.ServerStream.SendMsg(m)
}

// Client_ServiceDesc is the grpc.ServiceDesc for Client service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Client_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Client",
	HandlerType: (*ClientServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Create",
			Handler:       _Client_Create_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/client/client.proto",
}
