// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.7
// source: proto/coreSwitch/coreSwitch.proto

package coreSwitch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files     []byte `protobuf:"bytes,1,opt,name=files,proto3" json:"files,omitempty"`
	DirTarget string `protobuf:"bytes,2,opt,name=dirTarget,proto3" json:"dirTarget,omitempty"`
}

func (x *WriteReq) Reset() {
	*x = WriteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_coreSwitch_coreSwitch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReq) ProtoMessage() {}

func (x *WriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coreSwitch_coreSwitch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReq.ProtoReflect.Descriptor instead.
func (*WriteReq) Descriptor() ([]byte, []int) {
	return file_proto_coreSwitch_coreSwitch_proto_rawDescGZIP(), []int{0}
}

func (x *WriteReq) GetFiles() []byte {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *WriteReq) GetDirTarget() string {
	if x != nil {
		return x.DirTarget
	}
	return ""
}

type WriteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Progress uint32 `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
}

func (x *WriteRes) Reset() {
	*x = WriteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_coreSwitch_coreSwitch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRes) ProtoMessage() {}

func (x *WriteRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coreSwitch_coreSwitch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRes.ProtoReflect.Descriptor instead.
func (*WriteRes) Descriptor() ([]byte, []int) {
	return file_proto_coreSwitch_coreSwitch_proto_rawDescGZIP(), []int{1}
}

func (x *WriteRes) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

var File_proto_coreSwitch_coreSwitch_proto protoreflect.FileDescriptor

var file_proto_coreSwitch_coreSwitch_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x53, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x08, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x22, 0x26, 0x0a, 0x08, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x32, 0x2f, 0x0a, 0x0a, 0x43,
	0x6f, 0x72, 0x65, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x12, 0x21, 0x0a, 0x05, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x12, 0x09, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0e, 0x5a, 0x0c,
	0x2e, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_coreSwitch_coreSwitch_proto_rawDescOnce sync.Once
	file_proto_coreSwitch_coreSwitch_proto_rawDescData = file_proto_coreSwitch_coreSwitch_proto_rawDesc
)

func file_proto_coreSwitch_coreSwitch_proto_rawDescGZIP() []byte {
	file_proto_coreSwitch_coreSwitch_proto_rawDescOnce.Do(func() {
		file_proto_coreSwitch_coreSwitch_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_coreSwitch_coreSwitch_proto_rawDescData)
	})
	return file_proto_coreSwitch_coreSwitch_proto_rawDescData
}

var file_proto_coreSwitch_coreSwitch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_coreSwitch_coreSwitch_proto_goTypes = []interface{}{
	(*WriteReq)(nil), // 0: WriteReq
	(*WriteRes)(nil), // 1: WriteRes
}
var file_proto_coreSwitch_coreSwitch_proto_depIdxs = []int32{
	0, // 0: CoreSwitch.Write:input_type -> WriteReq
	1, // 1: CoreSwitch.Write:output_type -> WriteRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_coreSwitch_coreSwitch_proto_init() }
func file_proto_coreSwitch_coreSwitch_proto_init() {
	if File_proto_coreSwitch_coreSwitch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_coreSwitch_coreSwitch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_coreSwitch_coreSwitch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_coreSwitch_coreSwitch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coreSwitch_coreSwitch_proto_goTypes,
		DependencyIndexes: file_proto_coreSwitch_coreSwitch_proto_depIdxs,
		MessageInfos:      file_proto_coreSwitch_coreSwitch_proto_msgTypes,
	}.Build()
	File_proto_coreSwitch_coreSwitch_proto = out.File
	file_proto_coreSwitch_coreSwitch_proto_rawDesc = nil
	file_proto_coreSwitch_coreSwitch_proto_goTypes = nil
	file_proto_coreSwitch_coreSwitch_proto_depIdxs = nil
}
