// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.7
// source: proto/dataNode/datanode.proto

package dataNode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfo_NodeReplicationStatus int32

const (
	NodeInfo_SUCCESS NodeInfo_NodeReplicationStatus = 0
	NodeInfo_FAILED  NodeInfo_NodeReplicationStatus = 1
	NodeInfo_PENDING NodeInfo_NodeReplicationStatus = 2
)

// Enum value maps for NodeInfo_NodeReplicationStatus.
var (
	NodeInfo_NodeReplicationStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
		2: "PENDING",
	}
	NodeInfo_NodeReplicationStatus_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
		"PENDING": 2,
	}
)

func (x NodeInfo_NodeReplicationStatus) Enum() *NodeInfo_NodeReplicationStatus {
	p := new(NodeInfo_NodeReplicationStatus)
	*p = x
	return p
}

func (x NodeInfo_NodeReplicationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeInfo_NodeReplicationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dataNode_datanode_proto_enumTypes[0].Descriptor()
}

func (NodeInfo_NodeReplicationStatus) Type() protoreflect.EnumType {
	return &file_proto_dataNode_datanode_proto_enumTypes[0]
}

func (x NodeInfo_NodeReplicationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeInfo_NodeReplicationStatus.Descriptor instead.
func (NodeInfo_NodeReplicationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_dataNode_datanode_proto_rawDescGZIP(), []int{0, 0}
}

type CreateRes_CreateStatus int32

const (
	CreateRes_SUCCESS CreateRes_CreateStatus = 0
	CreateRes_FAILED  CreateRes_CreateStatus = 1
)

// Enum value maps for CreateRes_CreateStatus.
var (
	CreateRes_CreateStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	CreateRes_CreateStatus_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x CreateRes_CreateStatus) Enum() *CreateRes_CreateStatus {
	p := new(CreateRes_CreateStatus)
	*p = x
	return p
}

func (x CreateRes_CreateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateRes_CreateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dataNode_datanode_proto_enumTypes[1].Descriptor()
}

func (CreateRes_CreateStatus) Type() protoreflect.EnumType {
	return &file_proto_dataNode_datanode_proto_enumTypes[1]
}

func (x CreateRes_CreateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateRes_CreateStatus.Descriptor instead.
func (CreateRes_CreateStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_dataNode_datanode_proto_rawDescGZIP(), []int{3, 0}
}

type NodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID            string                         `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Address           string                         `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	GrpcPort          uint32                         `protobuf:"varint,3,opt,name=grpcPort,proto3" json:"grpcPort,omitempty"`
	ReplicationStatus NodeInfo_NodeReplicationStatus `protobuf:"varint,4,opt,name=replicationStatus,proto3,enum=NodeInfo_NodeReplicationStatus" json:"replicationStatus,omitempty"`
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataNode_datanode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataNode_datanode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_dataNode_datanode_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetGrpcPort() uint32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *NodeInfo) GetReplicationStatus() NodeInfo_NodeReplicationStatus {
	if x != nil {
		return x.ReplicationStatus
	}
	return NodeInfo_SUCCESS
}

type CreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	INodeID               string      `protobuf:"bytes,1,opt,name=iNodeID,proto3" json:"iNodeID,omitempty"`
	BlockID               string      `protobuf:"bytes,2,opt,name=blockID,proto3" json:"blockID,omitempty"`
	BlocksData            []byte      `protobuf:"bytes,3,opt,name=blocksData,proto3" json:"blocksData,omitempty"`
	ReplicationTarget     uint32      `protobuf:"varint,4,opt,name=replicationTarget,proto3" json:"replicationTarget,omitempty"`
	CurrentReplicated     uint32      `protobuf:"varint,5,opt,name=currentReplicated,proto3" json:"currentReplicated,omitempty"`
	ReplicationNodeTarget []*NodeInfo `protobuf:"bytes,6,rep,name=replicationNodeTarget,proto3" json:"replicationNodeTarget,omitempty"`
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataNode_datanode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataNode_datanode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_proto_dataNode_datanode_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReq) GetINodeID() string {
	if x != nil {
		return x.INodeID
	}
	return ""
}

func (x *CreateReq) GetBlockID() string {
	if x != nil {
		return x.BlockID
	}
	return ""
}

func (x *CreateReq) GetBlocksData() []byte {
	if x != nil {
		return x.BlocksData
	}
	return nil
}

func (x *CreateReq) GetReplicationTarget() uint32 {
	if x != nil {
		return x.ReplicationTarget
	}
	return 0
}

func (x *CreateReq) GetCurrentReplicated() uint32 {
	if x != nil {
		return x.CurrentReplicated
	}
	return 0
}

func (x *CreateReq) GetReplicationNodeTarget() []*NodeInfo {
	if x != nil {
		return x.ReplicationNodeTarget
	}
	return nil
}

type CreateResDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateResDetail) Reset() {
	*x = CreateResDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataNode_datanode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResDetail) ProtoMessage() {}

func (x *CreateResDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataNode_datanode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResDetail.ProtoReflect.Descriptor instead.
func (*CreateResDetail) Descriptor() ([]byte, []int) {
	return file_proto_dataNode_datanode_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status CreateRes_CreateStatus `protobuf:"varint,1,opt,name=status,proto3,enum=CreateRes_CreateStatus" json:"status,omitempty"`
	Detail *CreateResDetail       `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *CreateRes) Reset() {
	*x = CreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataNode_datanode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRes) ProtoMessage() {}

func (x *CreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataNode_datanode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRes.ProtoReflect.Descriptor instead.
func (*CreateRes) Descriptor() ([]byte, []int) {
	return file_proto_dataNode_datanode_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRes) GetStatus() CreateRes_CreateStatus {
	if x != nil {
		return x.Status
	}
	return CreateRes_SUCCESS
}

func (x *CreateRes) GetDetail() *CreateResDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type QueryStorageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryStorageReq) Reset() {
	*x = QueryStorageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataNode_datanode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStorageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStorageReq) ProtoMessage() {}

func (x *QueryStorageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataNode_datanode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStorageReq.ProtoReflect.Descriptor instead.
func (*QueryStorageReq) Descriptor() ([]byte, []int) {
	return file_proto_dataNode_datanode_proto_rawDescGZIP(), []int{4}
}

type QueryStorageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalStorage      uint64 `protobuf:"varint,1,opt,name=total_storage,json=totalStorage,proto3" json:"total_storage,omitempty"`
	ActualUsedStorage uint64 `protobuf:"varint,2,opt,name=actual_used_storage,json=actualUsedStorage,proto3" json:"actual_used_storage,omitempty"`
}

func (x *QueryStorageRes) Reset() {
	*x = QueryStorageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dataNode_datanode_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStorageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStorageRes) ProtoMessage() {}

func (x *QueryStorageRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataNode_datanode_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStorageRes.ProtoReflect.Descriptor instead.
func (*QueryStorageRes) Descriptor() ([]byte, []int) {
	return file_proto_dataNode_datanode_proto_rawDescGZIP(), []int{5}
}

func (x *QueryStorageRes) GetTotalStorage() uint64 {
	if x != nil {
		return x.TotalStorage
	}
	return 0
}

func (x *QueryStorageRes) GetActualUsedStorage() uint64 {
	if x != nil {
		return x.ActualUsedStorage
	}
	return 0
}

var File_proto_dataNode_datanode_proto protoreflect.FileDescriptor

var file_proto_dataNode_datanode_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65,
	0x2f, 0x64, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xe6, 0x01, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x67, 0x72, 0x70, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x67, 0x72, 0x70, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x4d, 0x0a, 0x11, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x11, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3d, 0x0a, 0x15, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x22, 0xfc, 0x01, 0x0a, 0x09, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x11, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x11, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x3f, 0x0a, 0x15, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x15, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64,
	0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x33, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8f, 0x01, 0x0a,
	0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x27, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x22, 0x11,
	0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x22, 0x66, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x61, 0x63, 0x74,
	0x75, 0x61, 0x6c, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x55, 0x73,
	0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x32, 0x64, 0x0a, 0x08, 0x44, 0x61, 0x74,
	0x61, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x0a, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x10, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dataNode_datanode_proto_rawDescOnce sync.Once
	file_proto_dataNode_datanode_proto_rawDescData = file_proto_dataNode_datanode_proto_rawDesc
)

func file_proto_dataNode_datanode_proto_rawDescGZIP() []byte {
	file_proto_dataNode_datanode_proto_rawDescOnce.Do(func() {
		file_proto_dataNode_datanode_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dataNode_datanode_proto_rawDescData)
	})
	return file_proto_dataNode_datanode_proto_rawDescData
}

var file_proto_dataNode_datanode_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_dataNode_datanode_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_dataNode_datanode_proto_goTypes = []interface{}{
	(NodeInfo_NodeReplicationStatus)(0), // 0: NodeInfo.NodeReplicationStatus
	(CreateRes_CreateStatus)(0),         // 1: CreateRes.CreateStatus
	(*NodeInfo)(nil),                    // 2: NodeInfo
	(*CreateReq)(nil),                   // 3: CreateReq
	(*CreateResDetail)(nil),             // 4: CreateResDetail
	(*CreateRes)(nil),                   // 5: CreateRes
	(*QueryStorageReq)(nil),             // 6: QueryStorageReq
	(*QueryStorageRes)(nil),             // 7: QueryStorageRes
}
var file_proto_dataNode_datanode_proto_depIdxs = []int32{
	0, // 0: NodeInfo.replicationStatus:type_name -> NodeInfo.NodeReplicationStatus
	2, // 1: CreateReq.replicationNodeTarget:type_name -> NodeInfo
	1, // 2: CreateRes.status:type_name -> CreateRes.CreateStatus
	4, // 3: CreateRes.detail:type_name -> CreateResDetail
	3, // 4: DataNode.Create:input_type -> CreateReq
	6, // 5: DataNode.QueryStorage:input_type -> QueryStorageReq
	5, // 6: DataNode.Create:output_type -> CreateRes
	7, // 7: DataNode.QueryStorage:output_type -> QueryStorageRes
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_dataNode_datanode_proto_init() }
func file_proto_dataNode_datanode_proto_init() {
	if File_proto_dataNode_datanode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dataNode_datanode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataNode_datanode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataNode_datanode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataNode_datanode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataNode_datanode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStorageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dataNode_datanode_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStorageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dataNode_datanode_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dataNode_datanode_proto_goTypes,
		DependencyIndexes: file_proto_dataNode_datanode_proto_depIdxs,
		EnumInfos:         file_proto_dataNode_datanode_proto_enumTypes,
		MessageInfos:      file_proto_dataNode_datanode_proto_msgTypes,
	}.Build()
	File_proto_dataNode_datanode_proto = out.File
	file_proto_dataNode_datanode_proto_rawDesc = nil
	file_proto_dataNode_datanode_proto_goTypes = nil
	file_proto_dataNode_datanode_proto_depIdxs = nil
}
