// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.7
// source: proto/nameNode/nameNode.proto

package nameNode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateJobQueueReq_Status int32

const (
	UpdateJobQueueReq_SUCCESS UpdateJobQueueReq_Status = 0
	UpdateJobQueueReq_FAILED  UpdateJobQueueReq_Status = 1
)

// Enum value maps for UpdateJobQueueReq_Status.
var (
	UpdateJobQueueReq_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
	}
	UpdateJobQueueReq_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILED":  1,
	}
)

func (x UpdateJobQueueReq_Status) Enum() *UpdateJobQueueReq_Status {
	p := new(UpdateJobQueueReq_Status)
	*p = x
	return p
}

func (x UpdateJobQueueReq_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateJobQueueReq_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_nameNode_nameNode_proto_enumTypes[0].Descriptor()
}

func (UpdateJobQueueReq_Status) Type() protoreflect.EnumType {
	return &file_proto_nameNode_nameNode_proto_enumTypes[0]
}

func (x UpdateJobQueueReq_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateJobQueueReq_Status.Descriptor instead.
func (UpdateJobQueueReq_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_nameNode_nameNode_proto_rawDescGZIP(), []int{0, 0}
}

type UpdateJobQueueReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobQueueID string                   `protobuf:"bytes,1,opt,name=jobQueueID,proto3" json:"jobQueueID,omitempty"`
	Status     UpdateJobQueueReq_Status `protobuf:"varint,2,opt,name=status,proto3,enum=UpdateJobQueueReq_Status" json:"status,omitempty"`
}

func (x *UpdateJobQueueReq) Reset() {
	*x = UpdateJobQueueReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nameNode_nameNode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateJobQueueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobQueueReq) ProtoMessage() {}

func (x *UpdateJobQueueReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nameNode_nameNode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobQueueReq.ProtoReflect.Descriptor instead.
func (*UpdateJobQueueReq) Descriptor() ([]byte, []int) {
	return file_proto_nameNode_nameNode_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateJobQueueReq) GetJobQueueID() string {
	if x != nil {
		return x.JobQueueID
	}
	return ""
}

func (x *UpdateJobQueueReq) GetStatus() UpdateJobQueueReq_Status {
	if x != nil {
		return x.Status
	}
	return UpdateJobQueueReq_SUCCESS
}

type UpdateJobQueueRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateJobQueueRes) Reset() {
	*x = UpdateJobQueueRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_nameNode_nameNode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateJobQueueRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobQueueRes) ProtoMessage() {}

func (x *UpdateJobQueueRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nameNode_nameNode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobQueueRes.ProtoReflect.Descriptor instead.
func (*UpdateJobQueueRes) Descriptor() ([]byte, []int) {
	return file_proto_nameNode_nameNode_proto_rawDescGZIP(), []int{1}
}

var File_proto_nameNode_nameNode_proto protoreflect.FileDescriptor

var file_proto_nameNode_nameNode_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x89, 0x01, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x6a, 0x6f, 0x62, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6a, 0x6f, 0x62, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x49, 0x44, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f,
	0x62, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x21, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x22, 0x13, 0x0a, 0x11, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73,
	0x32, 0x46, 0x0a, 0x08, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x3a, 0x0a, 0x0e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x12,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x12, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x6e, 0x61,
	0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_nameNode_nameNode_proto_rawDescOnce sync.Once
	file_proto_nameNode_nameNode_proto_rawDescData = file_proto_nameNode_nameNode_proto_rawDesc
)

func file_proto_nameNode_nameNode_proto_rawDescGZIP() []byte {
	file_proto_nameNode_nameNode_proto_rawDescOnce.Do(func() {
		file_proto_nameNode_nameNode_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_nameNode_nameNode_proto_rawDescData)
	})
	return file_proto_nameNode_nameNode_proto_rawDescData
}

var file_proto_nameNode_nameNode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_nameNode_nameNode_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_nameNode_nameNode_proto_goTypes = []interface{}{
	(UpdateJobQueueReq_Status)(0), // 0: UpdateJobQueueReq.Status
	(*UpdateJobQueueReq)(nil),     // 1: UpdateJobQueueReq
	(*UpdateJobQueueRes)(nil),     // 2: UpdateJobQueueRes
}
var file_proto_nameNode_nameNode_proto_depIdxs = []int32{
	0, // 0: UpdateJobQueueReq.status:type_name -> UpdateJobQueueReq.Status
	1, // 1: NameNode.UpdateJobQueue:input_type -> UpdateJobQueueReq
	2, // 2: NameNode.UpdateJobQueue:output_type -> UpdateJobQueueRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_nameNode_nameNode_proto_init() }
func file_proto_nameNode_nameNode_proto_init() {
	if File_proto_nameNode_nameNode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_nameNode_nameNode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateJobQueueReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_nameNode_nameNode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateJobQueueRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_nameNode_nameNode_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_nameNode_nameNode_proto_goTypes,
		DependencyIndexes: file_proto_nameNode_nameNode_proto_depIdxs,
		EnumInfos:         file_proto_nameNode_nameNode_proto_enumTypes,
		MessageInfos:      file_proto_nameNode_nameNode_proto_msgTypes,
	}.Build()
	File_proto_nameNode_nameNode_proto = out.File
	file_proto_nameNode_nameNode_proto_rawDesc = nil
	file_proto_nameNode_nameNode_proto_goTypes = nil
	file_proto_nameNode_nameNode_proto_depIdxs = nil
}
